@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FinanceTracker *-right-> "1" TransactionList
FinanceTracker *-right-> "1" UniqueCategoryList
UniqueCategoryList -[hidden]down- TransactionList

UniqueCategoryList *-right-> "*" Category
TransactionList o-right-> Transaction

Transaction -up-> "*" Category

Transaction *--> Title
Transaction *--> Amount
Transaction *--> Date
@enduml
