@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFinanceTracker <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FinanceTracker
Class ReadOnlyFinanceTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Transaction {
Class Transaction
Class Amount
Class Date
Class Title
Class TransactionList
}

Package Category {
Class Category
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FinanceTracker .up.|> ReadOnlyFinanceTracker

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FinanceTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FinanceTracker *--> "1" TransactionList
TransactionList o--> "*" Transaction
Transaction *--> Title
Transaction *--> Amount
Transaction *--> Date
Transaction *--> "*" Category

Title -[hidden]right-> Amount
Amount -[hidden]right-> Date

ModelManager -->"1" Transaction : filtered list
@enduml
