title: "Fine$$e"
theme: minima

header_pages:
  - Minutes.md
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-W16-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jekyll-spaceship
